indent_style = "Visual"
use_small_heuristics = "Max"
max_width = 120
wrap_comments = true
comment_width = 120
condense_wildcard_suffixes = true
format_strings = true
import_indent = "Visual"
imports_layout = "HorizontalVertical"
newline_style = "Unix"

reorder_imports = true #default
reorder_modules = true #default
reorder_impl_items = true

space_after_colon = true #default
space_before_colon = true

struct_field_align_threshold = 20

format_doc_comments = true
