#indent_style = "Visual"
indent_style = "Block"
use_small_heuristics = "Max"
max_width = 100
wrap_comments = true
comment_width = 100
condense_wildcard_suffixes = true
format_strings = true
#import_indent = "Visual"
import_indent = "Block"
imports_layout = "HorizontalVertical"
newline_style = "Unix"

reorder_imports = true #default
reorder_modules = true #default
reorder_impl_items = true

space_after_colon = true #default
space_before_colon = true

struct_field_align_threshold = 20

format_doc_comments = true
